services:
    hypergalaktisch_parallax.listener.hooks:
        class: Hypergalaktisch\ParallaxBundle\EventListener\HookListener
        public: true
        arguments:
            - "@contao.framework"
